# Generated by Django 4.1.5 on 2023-05-07 12:35

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
